### PR TITLE
Fix crash on newer Node.js versions and extend API

### PR DESCRIPTION
**Pull request by gerhardberger**
This PR updates the Node.js bindings in the repo so it won't crash on newer versions.

It also adds an extra `code` field to be returned to the API.

### CODE REVIEW

**Comment by jmcrthrs** [comment]
Which Node & Electron versions have you tested this library with?

I've tried with Node 8, 11  & 14, and Electron 9 but get the same response with each:

`
{
  code: 1000,
  message: 'Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1000 "(null)"'
}
`

I suspect this isn't the library, but actually an issue with my development setup, such as not having the correct entitlements or capabilities configured.

**Comment by gerhardberger** [comment]
I tried it with electron 12

yes, that issue is due to lack of entitlements

**Comment by jmcrthrs** [comment]
> I tried it with electron 12
> 
> yes, that issue is due to lack of entitlements

Yes I thought as much. I have added this package to a fresh Electron app, but I can't find any information on how to configure the application to use mac entitlements during development. 

The closest information I have found is in the [In-App Purchase](https://www.electronjs.org/docs/tutorial/in-app-purchases#change-the-cfbundleidentifier) guide. 

> To test In-App Purchase in development with Electron you'll have to change the CFBundleIdentifier in node_modules/electron/dist/Electron.app/Contents/Info.plist. You have to replace com.github.electron by the bundle identifier of the application you created with iTunes Connect.

Do I need to create a new XCode project and import the Electron application?

Thanks for any help you can provide.

**Comment by gerhardberger** [comment]
yea I think you have to build a release package of the electron app with correct provisioning profile and sign and notarize it

**Comment by jmcrthrs** [comment]
Ah so that suggests it's not possible to test the sign in with apple during development?

**Comment by jpalumickas** [comment]
Thanks @gerhardberger for PR. Released v0.5.0 version. Can you test if it's working now for you ? 🙂

**Pull request merged**
